import { ArrowRight, CalendarDays, Check, Coffee, Footprints, Heart, Moon, ShieldCheck, Sparkles, UsersRound, type LucideIcon } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";

const days = ["M", "T", "W", "T", "F", "S", "S"];

export function HomeDashboard() {
  return <div className="mx-auto flex max-w-[1240px] flex-col gap-5">
    <section className="grid gap-5 xl:grid-cols-[1.9fr_1fr]">
      <div className="hero-glow relative min-h-[230px] overflow-hidden rounded-2xl border border-[#e8ddff] p-6 md:p-8">
        <div className="relative z-10 max-w-[420px]"><p className="mb-2 text-sm font-semibold text-lamp">YOUR DAILY SPACE</p><h1 className="text-3xl font-bold tracking-tight text-ink md:text-[32px]">Welcome back, Sahil <span aria-hidden="true">🌙</span></h1><p className="mt-3 max-w-sm text-sm leading-6 text-ink-muted">Thanks for checking in. Small steps together can lead to meaningful change.</p><Link href="/checkin" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-lamp px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-lamp/90">Start check-in (60 sec) <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div>
        <div className="absolute bottom-[-17px] right-4 hidden h-40 w-52 rounded-t-[48%] border-[10px] border-white/45 bg-lamp/20 md:block" aria-hidden="true"><div className="absolute bottom-4 left-5 h-16 w-8 rounded-t-full bg-lamp/70" /><div className="absolute bottom-4 left-16 h-24 w-9 rounded-t-full bg-[#9676e8]" /><div className="absolute bottom-4 left-28 h-19 w-8 rounded-t-full bg-lamp/65" /></div>
      </div>
      <section aria-labelledby="streak-heading" className="dashboard-card rounded-2xl border border-border-subtle bg-white p-6"><h2 id="streak-heading" className="text-lg font-bold text-ink">Your Streak</h2><p className="mt-4 flex items-baseline gap-2"><span className="text-3xl">🔥</span><strong className="text-3xl">7</strong><span className="text-sm font-semibold text-ink-muted">days</span></p><p className="mt-2 text-sm text-ink-muted">Keep it going! You&apos;re doing great.</p><div className="mt-5 flex justify-between" aria-label="Seven day check-in streak">{days.map((day, index) => <span key={`${day}-${index}`} className="flex flex-col items-center gap-1 text-[11px] text-ink-muted"><span className={`flex h-6 w-6 items-center justify-center rounded-full ${index === 6 ? "border border-border-subtle bg-paper" : "bg-lamp text-white"}`}>{index < 6 && <Check className="h-3.5 w-3.5" aria-hidden="true" />}</span>{day}</span>)}</div></section>
    </section>
    <section className="grid gap-5 lg:grid-cols-[1.2fr_1fr_.75fr]">
      <section aria-labelledby="last-checkin-heading" className="dashboard-card rounded-2xl border border-border-subtle bg-white p-5"><div className="flex items-center justify-between"><h2 id="last-checkin-heading" className="flex items-center gap-2 text-base font-bold"><CalendarDays className="h-5 w-5 text-lamp" aria-hidden="true" />Your Last Check-in</h2><span className="text-xs font-semibold text-lamp">Today, 9:45 PM</span></div><div className="mt-5 grid grid-cols-3 divide-x divide-border-subtle text-center"><Metric title="How you felt" symbol="😟" value="Lonely, Exhausted" /><Metric title="What you needed" symbol="🌿" value="Relax" /><Metric title="Time" symbol={<Moon className="mx-auto h-6 w-6 text-lamp" aria-hidden="true" />} value="Night" /></div><div className="mt-5 flex items-center justify-between rounded-lg border border-[#e4d9ff] bg-lamp-tint px-4 py-3 text-sm text-ink-muted"><span>Thanks for sharing. It&apos;s okay to take things one small step at a time.</span><Heart className="ml-3 h-5 w-5 shrink-0 text-lamp" aria-hidden="true" /></div></section>
      <section aria-labelledby="action-heading" className="dashboard-card rounded-2xl border border-border-subtle bg-white p-5"><div className="flex items-center justify-between"><h2 id="action-heading" className="flex items-center gap-2 text-base font-bold"><Sparkles className="h-5 w-5 text-lamp" aria-hidden="true" />Tiny Action for You</h2><span className="rounded-full bg-moss-tint px-2.5 py-1 text-xs font-semibold text-moss">New</span></div><div className="mt-5 flex gap-4"><div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-xl bg-[#31255a] text-4xl">🌙</div><div><h3 className="font-bold">You&apos;re not alone at night.</h3><p className="mt-2 text-sm leading-5 text-ink-muted">Step outside for 2 minutes. Feel the air. Look at the sky. You&apos;ve got this.</p></div></div><div className="mt-5 flex gap-3"><Link href="/tiny-action" className="flex-1 rounded-lg bg-lamp px-3 py-2.5 text-center text-sm font-semibold text-white hover:bg-lamp/90">I&apos;ll Try This</Link><button className="flex-1 rounded-lg px-3 py-2.5 text-sm font-semibold text-lamp hover:bg-lamp-tint">Not Right Now</button></div></section>
      <section aria-labelledby="safety-heading" className="dashboard-card rounded-2xl border border-border-subtle bg-white p-5"><h2 id="safety-heading" className="flex items-center gap-2 text-base font-bold"><ShieldCheck className="h-5 w-5 text-lamp" aria-hidden="true" />Safety First</h2><p className="mt-4 text-sm leading-6 text-ink-muted">If you&apos;re feeling overwhelmed, we&apos;re here to help.</p><Link href="/safety" className="mt-5 flex items-center justify-center gap-2 rounded-lg border border-[#e4d9ff] px-3 py-2.5 text-sm font-semibold text-lamp hover:bg-lamp-tint">View Safety Plan <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link><Link href="/professional-help" className="mt-3 flex items-center justify-between border-t border-border-subtle pt-4 text-sm font-medium">Find professional help <ArrowRight className="h-4 w-4 text-lamp" aria-hidden="true" /></Link></section>
    </section>
    <section className="grid gap-5 lg:grid-cols-[1.3fr_1fr]">
      <section aria-labelledby="hangouts-heading" className="dashboard-card rounded-2xl border border-border-subtle bg-white p-5"><div className="flex items-center justify-between"><h2 id="hangouts-heading" className="flex items-center gap-2 text-lg font-bold"><CalendarDays className="h-5 w-5 text-lamp" aria-hidden="true" />Discover Campus Hangouts</h2><Link href="/community" className="text-xs font-semibold text-lamp">View all</Link></div><div className="mt-3 divide-y divide-border-subtle"><Hangout icon={Coffee} title="Chai & Chat" copy="Casual conversations over chai" time="Today, 6:00 PM" place="Library Lawn" action="Join" /><Hangout icon={Footprints} title="Mindful Walk" copy="A calm walk around campus" time="Tomorrow, 7:00 AM" place="Main Gate" action="Interested" /><Hangout icon={Sparkles} title="Open Mic Night" copy="Share your talent, your way" time="Fri, 6:30 PM" place="Auditorium" action="Interested" /></div></section>
      <section aria-labelledby="people-heading" className="dashboard-card rounded-2xl border border-border-subtle bg-white p-5"><div className="flex items-center justify-between"><h2 id="people-heading" className="flex items-center gap-2 text-lg font-bold"><UsersRound className="h-5 w-5 text-lamp" aria-hidden="true" />People You Might Connect With</h2><Link href="/community" className="text-xs font-semibold text-lamp">View all</Link></div><div className="mt-3 divide-y divide-border-subtle"><Person name="Ananya" detail="Third Year · Psychology" initial="A" /><Person name="Rohan" detail="Second Year · CSE" initial="R" /><Person name="Meera" detail="Third Year · Design" initial="M" /></div></section>
    </section>
    <footer className="flex flex-wrap justify-between gap-3 px-1 pt-1 text-xs text-ink-muted"><span>© 2026 Coo_Do · You&apos;re not alone here.</span><span className="flex gap-5"><Link href="/journal">Journal</Link><a href="#privacy">Privacy</a><a href="#help">Help</a></span></footer>
  </div>;
}

function Metric({ title, symbol, value }: { title: string; symbol: ReactNode; value: string }) { return <div><p className="text-xs text-ink-muted">{title}</p><div className="mt-2 flex h-7 items-center justify-center text-2xl">{symbol}</div><p className="mt-1 text-xs font-medium">{value}</p></div>; }
function Hangout({ icon: Icon, title, copy, time, place, action }: { icon: LucideIcon; title: string; copy: string; time: string; place: string; action: string }) { return <div className="grid grid-cols-[auto_1fr_auto] items-center gap-3 py-3"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-lamp-tint text-lamp"><Icon className="h-5 w-5" aria-hidden="true" /></span><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-0.5 text-xs text-ink-muted">{copy}</p></div><div className="hidden text-right text-xs text-ink-muted sm:block"><p>{time}</p><p>{place}</p></div><Link href="/community" className={`rounded-lg border px-3 py-2 text-xs font-semibold ${action === "Join" ? "border-lamp bg-lamp text-white" : "border-border-subtle text-ink"}`}>{action}</Link></div>; }
function Person({ name, detail, initial }: { name: string; detail: string; initial: string }) { return <div className="flex items-center gap-3 py-3"><span className="relative flex h-10 w-10 items-center justify-center rounded-full bg-lamp-tint text-sm font-bold text-lamp">{initial}<span className="absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-white bg-moss" /></span><div className="min-w-0 flex-1"><h3 className="text-sm font-bold">{name}</h3><p className="truncate text-xs text-ink-muted">{detail}</p></div><Link href="/community" className="rounded-lg border border-[#e4d9ff] px-3 py-2 text-xs font-semibold text-lamp hover:bg-lamp-tint">Connect</Link></div>; }
