import { CalendarCheck, ExternalLink, LifeBuoy, MessageCircleHeart, ShieldCheck, type LucideIcon } from "lucide-react";
import Link from "next/link";
import { internalApiFetch } from "@/lib/core-api-server";
import { openProfessionalResourceAction } from "./actions";

interface ProfessionalResource {
  id: string; category: string; title: string; summary: string;
  contact_label: string | null; contact_value: string | null; contact_uri: string | null;
  booking_steps: string[]; what_to_expect: string | null; opening_lines: string[]; last_verified_at: string | null;
}

export default async function ProfessionalHelpPage() {
  let resources: ProfessionalResource[] = [];
  let unavailable = false;
  try { resources = await internalApiFetch<ProfessionalResource[]>("/internal/professional-resources?region=India"); } catch { unavailable = true; }
  return <div className="mx-auto flex max-w-4xl flex-col gap-8 pb-8">
    <header className="max-w-2xl"><p className="text-sm font-semibold text-lamp">PROFESSIONAL HELP</p><h1 className="mt-2 font-display text-3xl text-ink">Real support, without the guesswork</h1><p className="mt-3 text-sm leading-6 text-ink-muted">Reaching out can feel like a big step. This page explains what support can look like and gives you a few words to start with — no check-in required.</p></header>
    <section className="grid gap-4 md:grid-cols-3" aria-label="What to expect from professional help"><InfoCard icon={LifeBuoy} title="What it can look like" copy="A first conversation is usually about what has been hard lately and what kind of support could help. You can share only what feels okay." /><InfoCard icon={CalendarCheck} title="How to begin" copy="Choose one option below, call or book when you are ready, and say you are looking for support. You do not need a complete story first." /><InfoCard icon={MessageCircleHeart} title="Words you can borrow" copy="Use an opening line below as-is, change it, or simply say that you are not sure how to begin." /></section>
    {unavailable ? <p role="alert" className="rounded-xl border border-clay/20 bg-clay-tint p-4 text-sm text-clay">The support directory is temporarily unavailable. You can still visit the <Link className="font-semibold underline" href="/safety">Safety Center</Link> for immediate-support options.</p> : resources.length === 0 ? <p className="rounded-xl border border-border-subtle bg-paper-raised p-4 text-sm text-ink-muted">No resources have been published for this region yet. Please use the Safety Center for immediate-support options.</p> : <section aria-labelledby="directory-heading" className="space-y-4"><div><h2 id="directory-heading" className="font-display text-2xl text-ink">Support directory</h2><p className="mt-1 text-sm text-ink-muted">Human-curated information, not AI-generated. Contact details are shown with their most recent review date.</p></div><div className="grid gap-4 md:grid-cols-2">{resources.map((resource) => <ResourceCard key={resource.id} resource={resource} />)}</div></section>}
    <Link href="/safety" className="flex items-start gap-3 rounded-xl border border-[#e4d9ff] bg-lamp-tint p-4 text-sm text-ink hover:bg-[#eee7ff]"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-lamp" aria-hidden="true" /><span><strong>Need immediate support?</strong><br /><span className="text-ink-muted">The Safety Center has crisis resources and clear next steps.</span></span></Link>
  </div>;
}

function InfoCard({ icon: Icon, title, copy }: { icon: LucideIcon; title: string; copy: string }) { return <section className="rounded-xl border border-border-subtle bg-white p-5"><Icon className="h-5 w-5 text-lamp" aria-hidden="true" /><h2 className="mt-3 font-bold text-ink">{title}</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{copy}</p></section>; }
function ResourceCard({ resource }: { resource: ProfessionalResource }) { return <article className="rounded-2xl border border-border-subtle bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-lamp">{resource.category}</p><h3 className="mt-1 text-lg font-bold text-ink">{resource.title}</h3><p className="mt-2 text-sm leading-6 text-ink-muted">{resource.summary}</p>{resource.contact_value && <div className="mt-4 rounded-lg bg-paper p-3"><p className="text-xs text-ink-muted">{resource.contact_label ?? "Contact"}</p>{resource.contact_uri ? <form action={openProfessionalResourceAction} className="mt-1"><input type="hidden" name="resourceId" value={resource.id} /><button type="submit" className="inline-flex items-center gap-1 font-semibold text-lamp hover:underline">{resource.contact_value}<ExternalLink className="h-3.5 w-3.5" aria-hidden="true" /></button></form> : <p className="mt-1 font-semibold text-ink">{resource.contact_value}</p>}</div>}<Details title="How to start" items={resource.booking_steps} /><Details title="What to expect" text={resource.what_to_expect} /><Details title="What you could say" items={resource.opening_lines} />{resource.last_verified_at && <p className="mt-4 text-xs text-ink-muted">Directory entry reviewed {new Date(resource.last_verified_at).toLocaleDateString()}</p>}</article>; }
function Details({ title, text, items = [] }: { title: string; text?: string | null; items?: string[] }) { if (!text && items.length === 0) return null; return <details className="mt-4 border-t border-border-subtle pt-3"><summary className="cursor-pointer text-sm font-semibold text-ink">{title}</summary>{text && <p className="mt-2 text-sm leading-6 text-ink-muted">{text}</p>}{items.length > 0 && <ol className="mt-2 list-decimal space-y-1 pl-5 text-sm leading-6 text-ink-muted">{items.map((item) => <li key={item}>{item}</li>)}</ol>}</details>; }
