"""Deterministic support copy for a safety flag; never generated by a model.

R&D Sections 10 and 14-G require the classifier to flag only. It must not
compose a reply, diagnose, contact anyone, promise confidentiality, or trigger
an automatic escalation. These scripts are intentionally calm, brief, and
reviewable. Future contributors must not replace them with provider output.
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class SupportScript:
    id: str
    title: str
    body: str
    urgency: str


SCRIPTS: dict[str, SupportScript] = {
    "elevated_v1": SupportScript(
        id="elevated_v1",
        title="You deserve support right now.",
        body=(
            "It sounds like things may feel especially heavy. You do not have to handle this "
            "alone. If it feels helpful, reach out to someone you trust or use one of the "
            "support resources below."
        ),
        urgency="elevated",
    ),
    "crisis_v1": SupportScript(
        id="crisis_v1",
        title="Your safety matters right now.",
        body=(
            "Please pause and contact an immediate support resource below, or someone nearby "
            "you trust. If you may be in immediate danger, call your local emergency number now."
        ),
        urgency="crisis",
    ),
}


def script_for(flag_level: str) -> SupportScript | None:
    if flag_level == "crisis":
        return SCRIPTS["crisis_v1"]
    if flag_level == "elevated":
        return SCRIPTS["elevated_v1"]
    return None
