"""phase 2: auth fields on users, data_requests table

Revision ID: 9b33b7bc1eac
Revises: d59803e0ff54
Create Date: 2026-08-23 11:44:10.640464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b33b7bc1eac'
down_revision: Union[str, Sequence[str], None] = 'd59803e0ff54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Enum('EXPORT', 'DELETION', name='data_request_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'DENIED', name='data_request_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_requests_user_id'), 'data_requests', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.alter_column('users', 'auth_subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'auth_subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_data_requests_user_id'), table_name='data_requests')
    op.drop_table('data_requests')
    # ### end Alembic commands ###
