"""phase 0 mvp tables

Revision ID: d59803e0ff54
Revises: 
Create Date: 2026-08-22 04:50:53.663607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd59803e0ff54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_ref', sa.UUID(), nullable=False),
    sa.Column('flag_level', sa.Enum('ELEVATED', 'CRISIS', name='safety_flag_level'), nullable=False),
    sa.Column('source', sa.Enum('CHECKIN_FREETEXT', 'AI_NAVIGATOR', 'COMMUNITY_POST', 'JOURNAL', name='safety_source'), nullable=False),
    sa.Column('response_template_id', sa.String(), nullable=False),
    sa.Column('flagged_text', sa.Text(), nullable=True),
    sa.Column('escalation_status', sa.Enum('RESOURCE_SHOWN', 'HUMAN_REVIEW_PENDING', 'HUMAN_REVIEWED', 'RESOLVED', name='escalation_status'), nullable=False),
    sa.Column('reviewer_ref', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_user_ref'), 'safety_events', ['user_ref'], unique=False)
    op.create_table('tiny_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('ladder_parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ladder_parent_id'], ['tiny_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiny_actions_category'), 'tiny_actions', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_subject', sa.String(), nullable=False),
    sa.Column('pseudonymous_display_name', sa.String(), nullable=True),
    sa.Column('age_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=True)
    op.create_table('checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feelings', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('stated_need', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Enum('AI_CHAT', 'ANONYMOUS_COMMUNITY', 'MATCHING_VISIBILITY', 'INSTITUTIONAL_DATA_SHARING', name='consent_type'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('privacy_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_visible_in_matching', sa.Boolean(), nullable=False),
    sa.Column('display_name_visible_in_rooms', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_settings_user_id'), 'privacy_settings', ['user_id'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('action_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tiny_action_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'COMPLETED', 'SKIPPED', 'REDUCED', name='action_attempt_status'), nullable=False),
    sa.Column('related_checkin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_checkin_id'], ['checkins.id'], ),
    sa.ForeignKeyConstraint(['tiny_action_id'], ['tiny_actions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_attempts_tiny_action_id'), 'action_attempts', ['tiny_action_id'], unique=False)
    op.create_index(op.f('ix_action_attempts_user_id'), 'action_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_attempts_user_id'), table_name='action_attempts')
    op.drop_index(op.f('ix_action_attempts_tiny_action_id'), table_name='action_attempts')
    op.drop_table('action_attempts')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_privacy_settings_user_id'), table_name='privacy_settings')
    op.drop_table('privacy_settings')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tiny_actions_category'), table_name='tiny_actions')
    op.drop_table('tiny_actions')
    op.drop_index(op.f('ix_safety_events_user_ref'), table_name='safety_events')
    op.drop_table('safety_events')
    # ### end Alembic commands ###
