import { ExternalLink, Phone, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { getCrisisResources } from "@/safety/resources.server";

export default async function SafetyPage() {
  const resourceConfig = await getCrisisResources();
  return <div className="mx-auto max-w-3xl space-y-6">
    <section className="rounded-2xl border border-[#e4d9ff] bg-lamp-tint p-6 md:p-8"><ShieldCheck className="h-8 w-8 text-lamp" aria-hidden="true" /><h1 className="mt-4 text-3xl font-bold tracking-tight text-ink">Safety Center</h1><p className="mt-3 max-w-2xl leading-6 text-ink-muted">If things feel overwhelming, support is available. You choose whether to contact a resource or someone you trust.</p></section>
    <section aria-labelledby="resources-heading" className="dashboard-card rounded-2xl border border-border-subtle bg-white p-6"><h2 id="resources-heading" className="text-xl font-bold text-ink">Immediate support resources</h2>{resourceConfig ? <><p className="mt-2 text-sm text-ink-muted">{resourceConfig.region} · {resourceConfig.emergency_note}</p><div className="mt-5 divide-y divide-border-subtle">{resourceConfig.resources.map((resource) => <a key={resource.name} href={resource.phone_uri} className="flex items-center justify-between gap-4 py-4 transition hover:text-lamp"><span><span className="block font-semibold text-ink">{resource.name}</span><span className="mt-1 block text-sm text-ink-muted">{resource.description}</span></span><span className="flex shrink-0 items-center gap-2 text-sm font-bold text-lamp"><Phone className="h-4 w-4" aria-hidden="true" />{resource.phone}</span></a>)}</div></> : <p role="alert" className="mt-3 text-sm leading-6 text-clay">Resource details are temporarily unavailable. If you may be in immediate danger, call your local emergency number now or contact someone nearby you trust.</p>}</section>
    <section className="rounded-2xl border border-border-subtle bg-white p-6"><h2 className="text-lg font-bold text-ink">How this works</h2><p className="mt-2 text-sm leading-6 text-ink-muted">When a future text feature identifies possible crisis language, Coo_Do immediately shows this support information. It does not diagnose you, automatically contact anyone, or promise confidentiality it cannot guarantee.</p><div className="mt-4 flex flex-wrap gap-4"><Link href="/professional-help" className="inline-flex items-center gap-2 text-sm font-semibold text-lamp hover:underline">Explore professional support <ExternalLink className="h-4 w-4" aria-hidden="true" /></Link><Link href="/trusted-contacts?scenario=feeling_overwhelmed" className="inline-flex items-center gap-2 text-sm font-semibold text-lamp hover:underline">Reach out to someone you trust <ExternalLink className="h-4 w-4" aria-hidden="true" /></Link></div><p className="mt-3 text-xs leading-5 text-ink-muted">This is optional. Coo_Do never contacts a trusted person unless you choose to open a message yourself.</p></section>
  </div>;
}
